# Generated by Django 5.2.10 on 2026-01-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_url_user_bio_user_favorite_sports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
