# Generated by Django 5.2.10 on 2026-02-01 01:35

import snowflake_id.django_field
import snowflake_id.generator
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=snowflake_id.django_field.DjangoSnowflakeIDField(
                default=snowflake_id.generator.SnowflakeGenerator.generate,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
