# Generated by Django 5.2.10 on 2026-01-27

import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        CreateExtension("postgis"),
        migrations.RenameField(
            model_name="event",
            old_name="location",
            new_name="location_text",
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                null=True,
                srid=4326,
            ),
        ),
    ]
