# Generated by Django 5.2.10 on 2026-01-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_postgis_location_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="location_text",
        ),
    ]

