# Generated by Codex on 2026-01-27

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.contrib.postgres.indexes import GistIndex
from django.db import migrations, models


DEFAULT_LATITUDE = -15.793889
DEFAULT_LONGITUDE = -47.882778
DEFAULT_SRID = 4326


def backfill_event_locations(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    default_point = Point(DEFAULT_LONGITUDE, DEFAULT_LATITUDE, srid=DEFAULT_SRID)
    Event.objects.filter(location__isnull=True).update(location=default_point)


def noop_reverse(apps, schema_editor):
    # No safe reverse for the backfill.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_location_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.RunPython(backfill_event_locations, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True,
                srid=4326,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=GistIndex(fields=["location"], name="events_location_gist_idx"),
        ),
    ]
