# Generated by Codex on 2026-01-30

from django.db import migrations, models


DEFAULT_CATEGORIES = [
    ("Esportivo", "esportivo", "Eventos esportivos e atividades físicas."),
    ("Familiar", "familiar", "Encontros em família e eventos privados."),
    ("Trabalho", "trabalho", "Reuniões e eventos corporativos."),
    ("Social", "social", "Eventos sociais e encontros informais."),
    ("Estudo", "estudo", "Grupos de estudo e aulas."),
    ("Outro", "outro", "Eventos que não se encaixam nas categorias acima."),
]


def create_default_categories(apps, schema_editor):
    EventCategory = apps.get_model("events", "EventCategory")
    for name, slug, description in DEFAULT_CATEGORIES:
        EventCategory.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "description": description, "is_active": True},
        )


def assign_default_category(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    EventCategory = apps.get_model("events", "EventCategory")
    default_category = EventCategory.objects.filter(slug="esportivo").first()
    if default_category:
        Event.objects.filter(category__isnull=True).update(category=default_category)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_location_requirements"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Event categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="events",
                to="events.eventcategory",
            ),
        ),
        migrations.RunPython(create_default_categories, reverse_code=noop_reverse),
        migrations.RunPython(assign_default_category, reverse_code=noop_reverse),
    ]
