# Generated by Codex on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="events",
                to="events.eventcategory",
            ),
        ),
    ]
