# Generated by Django 5.2.10 on 2026-02-01 01:35

import snowflake_id.django_field
import snowflake_id.generator
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_event_category_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=snowflake_id.django_field.DjangoSnowflakeIDField(
                default=snowflake_id.generator.SnowflakeGenerator.generate,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="id",
            field=snowflake_id.django_field.DjangoSnowflakeIDField(
                default=snowflake_id.generator.SnowflakeGenerator.generate,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="event",
            table="events",
        ),
        migrations.AlterModelTable(
            name="eventcategory",
            table="events-categories",
        ),
        migrations.AlterModelTable(
            name="participation",
            table="events-participation",
        ),
    ]
